name: continuous-integration
on: [push, pull_request]

jobs:
  linux-os:
    runs-on: ubuntu-20.04
    steps:
    - name: Update APT
      run: sudo apt-get update
    - name: Install Dependencies
      run: |
        sudo apt-get install --assume-yes build-essential git make cmake autoconf automake \
                                          libtool pkg-config libasound2-dev libpulse-dev libaudio-dev \
                                          libjack-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev \
                                          libxfixes-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev \
                                          libgl1-mesa-dev libdbus-1-dev libudev-dev libgles2-mesa-dev \
                                          libegl1-mesa-dev libibus-1.0-dev fcitx-libs-dev libsamplerate0-dev \
                                          libsndio-dev libwayland-dev libxkbcommon-dev libdrm-dev libgbm-dev
    - name: Checkout love-appimage-source
      uses: actions/checkout@v3
      with:
        repository: alexjgriffith/love-appimage-source
        ref: 11.x-lua5.4
    - name: Checkout LÖVE
      uses: actions/checkout@v3
      with:
        path: love2d-11.5-lua5.4
    - name: Get Dependencies for AppImage
      shell: python
      env:
        LOVE_BRANCH: 11.5-lua5.4
      run: |
        import os
        for i in range(250):
            if os.system(f"make getdeps LOVE_BRANCH={os.environ['LOVE_BRANCH']}") == 0:
                raise SystemExit(0)
        raise Exception("make getdeps failed")
    - name: Build AppImage
      run: make LOVE_BRANCH=11.5-lua5.4
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: love-x86_64.AppImage
        path: love-11.5-lua5.4.AppImage
  windows-os:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [Win32, x64]
    steps:
    - name: Clone Megasource
      uses: actions/checkout@v3
      with:
        path: megasource
        repository: alexjgriffith/megasource
        ref: 11.5-lua5.4
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: megasource/libs/love
        ref: 11.5-lua5.4
    - name: Configure
      shell: cmd
      env:
        PLATFORM: ${{ matrix.platform }}
      run: cmake -Bbuild -Hmegasource -T v142 -A %PLATFORM% -DLUA_54=1 -DLOVE_JIT=0 -DCMAKE_INSTALL_PREFIX=%CD%\install
    - name: Install
      shell: cmd
      run: cmake --build build --config Release --target install -j2
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: love-windows-lu54-${{ matrix.platform }}
        path: install
